### ISSUE TITLE
[Feat] Automatic Release

### ISSUE THREAD

**Issue by dme-compunet** [kikipoulet/SukiUI#358]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

Currently it seems that publishing packages to NuGet is done manually,
how about a workflow file that will build and publish the packages automatically when the trigger is a tag push to the repository,
consider the following workflow file:

```yml
name: Build & Publish

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  VERSION: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: |
          dotnet build -c Release SukiUI/SukiUI.csproj -p:Version=${{ env.VERSION }}
          dotnet build -c Release SukiUI.Dock/SukiUI.Dock.csproj -p:Version=${{ env.VERSION }}

      - name: Pack
        run: |
          dotnet pack -c Release -o . SukiUI/SukiUI.csproj -p:Version=${{ env.VERSION }}
          dotnet pack -c Release -o . SukiUI.Dock/SukiUI.Dock.csproj -p:Version=${{ env.VERSION }}

      - name: Publish To NuGet
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ env.VERSION }}
          --repo ${{ github.event.repository.full_name }}
          --title ${{ env.VERSION }}
          --generate-notes
          --verify-tag
```

This workflow will also create a release on GitHub, all you have to do is just push a tag named of the version, at a certain point in the repository, and all the operations will be performed automatically.

Note: The tag name must be match to: `*.*.*`

**Important note:** For this to work, you need to create an API key in NuGet and put it in the repository secrets under the name: `NUGET_API_KEY`

### Package Version

6
